# Generated by Django 5.1.5 on 2025-02-03 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('description', models.TextField(blank=True)),
                ('max_appointments_per_day', models.IntegerField(default=10)),
                ('appointment_interval', models.PositiveIntegerField(default=15)),
                ('open_from', models.TimeField(blank=True, null=True)),
                ('open_until', models.TimeField(blank=True, null=True)),
                ('appointments_per_morning', models.IntegerField(default=5)),
                ('appointments_per_afternoon', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate_part1', models.CharField(blank=True, max_length=5, null=True)),
                ('license_plate_part2', models.CharField(blank=True, max_length=5, null=True)),
                ('license_plate_part3', models.CharField(blank=True, max_length=5, null=True)),
                ('license_plate_part4', models.CharField(blank=True, max_length=5, null=True)),
                ('color', models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('gray', 'Gray'), ('blue', 'Blue'), ('red', 'Red'), ('green', 'Green'), ('yellow', 'Yellow'), ('silver', 'Silver'), ('orange', 'Orange'), ('brown', 'Brown')], max_length=20)),
                ('brand', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('issue', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.user')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.garage')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.vehicle')),
            ],
        ),
    ]
